#!/bin/bash

install-podman () {
    # Check for podman install
    if [[ $(which podman) && $(podman --version) ]]; then
            echo "Podman is already installed, skipping..."
        else
            echo "Podman is not installed, installing..."
            apt install podman podman-compose podman-docker authbind -y
    fi
}

setup-podman-user () {
    # Setup podman registries
    mkdir -p "/home/${DUSER}/.conf/containers"
    echo "unqualified-search-registries = [${PODMAN_REG}]" > "/home/${DUSER}/.conf/containers/registries.conf"

    # Enable podman socket for ${DUSER}
    sudo -i -u ${DUSER} systemctl --user enable --now podman.socket

    # Allow ${DUSER} to keep containers running after logout
    loginctl enable-linger ${DUSER}
}


# Saved for reference, but not used
<<COMMENTBLOCK
setup-priv-ports () {
    PRIV_PORT="${1}"
    touch /etc/authbind/byport/${PRIV_PORT}
    chown root:${DUSER} /etc/authbind/byport/${PRIV_PORT}
    chmod 550 /etc/authbind/byport/${PRIV_PORT}
}
COMMENTBLOCK

setup-priv-ports () {
    setcap cap_net_bind_service=+ep /usr/libexec/podman/rootlessport
}