#!/bin/bash

remove-border0 () {
    echo y | border0 connector uninstall
    apt purge border0 -y
    rm $(which border0)
    rm -r /etc/border0
    systemctl disable --now webmin-login-proxy
    rm -r /etc/webmin-border0-proxy
    rm -r /usr/share/webmin-border0-proxy
}